#!/bin/bash

RCM_EXTENSION_VERSION=0.11.0-alpha.6

# Usage Functions.
usage() {
    cat << EOF
Usage: rcm-postfix-multiple-certificate-ispconfig [options]

Options:
   --fqdn *
        Fully Qualified Domain Name of the certificate, for example: \`server1.example.org\`.
    --tls-certificate *
        TLS Certificate.
        Populate value from variable TLS_CERTIFICATE.
    --tls-certificate-key *
        TLS Certificate.
        Populate value from variable TLS_CERTIFICATE_KEY.

Global Options:
   --version
        Print version of this script.
   --help
        Show this help.

Environment Variables:
   POSTFIX_CONFIG_DIR
        Default to $POSTFIX_CONFIG_DIR
   POSTFIX_CONFIG_FILE_VMAIL_SSL
        Default to $POSTFIX_CONFIG_FILE_VMAIL_SSL
   MAILBOX_HOST
        Default to $MAILBOX_HOST

Dependency:
   rcm-postfix-multiple-certificate
EOF
}

# Prevent scripts from being executed directly.
[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh.
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --fqdn=*) fqdn="${1#*=}"; shift ;;
        --fqdn) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then fqdn="$2"; shift; fi; shift ;;
        --tls-certificate-key=*) tls_certificate_key="${1#*=}"; shift ;;
        --tls-certificate-key) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then tls_certificate_key="$2"; shift; fi; shift ;;
        --tls-certificate=*) tls_certificate="${1#*=}"; shift ;;
        --tls-certificate) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then tls_certificate="$2"; shift; fi; shift ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Define variables and constants.
POSTFIX_CONFIG_DIR=${POSTFIX_CONFIG_DIR:=/etc/postfix}
POSTFIX_CONFIG_FILE_VMAIL_SSL=${POSTFIX_CONFIG_FILE_VMAIL_SSL:=${POSTFIX_CONFIG_DIR}/vmail_ssl.map}
MAILBOX_HOST=${MAILBOX_HOST:=hostmaster}

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

# ------------------------------------------------------------------------------

# Title.
title rcm-postfix-multiple-certificate-ispconfig
____

# Dependency.

# Functions.
isDirExists() {
    # global used:
    # global modified: found, notfound
    # function used: __
    found=
    notfound=
    if [ -d "$1" ];then
        __ Direktori '`'$(basename "$1")'`' ditemukan.
        found=1
    else
        __ Direktori '`'$(basename "$1")'`' tidak ditemukan.
        notfound=1
    fi
}

# Require, validate, and populate value.
chapter Variable dump.
[ -n "$fast" ] && isfast=' --fast' || isfast=''
code 'MAILBOX_HOST="'$MAILBOX_HOST'"'
code 'POSTFIX_CONFIG_DIR="'$POSTFIX_CONFIG_DIR'"'
code 'POSTFIX_CONFIG_FILE_VMAIL_SSL="'$POSTFIX_CONFIG_FILE_VMAIL_SSL'"'
if [ -z "$fqdn" ];then
    error "Argument --fqdn required."; x
fi
code 'fqdn="'$fqdn'"'
# If not set in argument, try load from environment.
[ -z "$tls_certificate" ] && tls_certificate="$TLS_CERTIFICATE"
[ -z "$tls_certificate_key" ] && tls_certificate_key="$TLS_CERTIFICATE_KEY"
if [ -z "$tls_certificate" ];then
    error "Argument --tls-certificate or variable TLS_CERTIFICATE required."; x
fi
code tls_certificate="$tls_certificate"
if [ -z "$tls_certificate_key" ];then
    error "Argument --tls-certificate-key or variable TLS_CERTIFICATE_KEY required."; x
fi
code tls_certificate_key="$tls_certificate_key"
[ -f "$tls_certificate" ] || fileMustExists "$tls_certificate"
[ -f "$tls_certificate_key" ] || fileMustExists "$tls_certificate_key"
____

INDENT+="    " \
rcm-postfix-multiple-certificate $isfast \
    --ssl-cert="$tls_certificate" \
    --ssl-key="$tls_certificate_key" \
    --fqdn="$fqdn" \
    --additional-config-file="$POSTFIX_CONFIG_FILE_VMAIL_SSL" \
    ; [ ! $? -eq 0 ] && x

exit 0

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# )
# VALUE=(
# --fqdn
# --tls-certificate
# --tls-certificate-key
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# CSV=(
# )
# EOF
# clear
