#!/bin/bash

# --- Generated by parse-options.sh.
_new_arguments=()

while [[ $# -gt 0 ]]; do
    case "$1" in
        --help|-h) help=1; shift ;;
        --autopopulate-ip-address) autopopulate_ip_address=1; shift ;;
        --digitalocean-token=*) digitalocean_token="${1#*=}"; shift ;;
        --digitalocean-token) if [[ ! $2 == "" && ! $2 =~ ^-[^-] ]]; then digitalocean_token="$2"; shift; fi; shift ;;
        --dkim-selector=*) dkim_selector="${1#*=}"; shift ;;
        --dkim-selector) if [[ ! $2 == "" && ! $2 =~ ^-[^-] ]]; then dkim_selector="$2"; shift; fi; shift ;;
        --hostname=*) hostname="${1#*=}"; shift ;;
        --hostname) if [[ ! $2 == "" && ! $2 =~ ^-[^-] ]]; then hostname="$2"; shift; fi; shift ;;
        --letsencrypt=*) letsencrypt="${1#*=}"; shift ;;
        --letsencrypt) if [[ ! $2 == "" && ! $2 =~ ^-[^-] ]]; then letsencrypt="$2"; shift; else letsencrypt=1; fi; shift ;;
        --mailbox-admin=*) mailbox_admin="${1#*=}"; shift ;;
        --mailbox-admin) if [[ ! $2 == "" && ! $2 =~ ^-[^-] ]]; then mailbox_admin="$2"; shift; fi; shift ;;
        --mailbox-host=*) mailbox_host="${1#*=}"; shift ;;
        --mailbox-host) if [[ ! $2 == "" && ! $2 =~ ^-[^-] ]]; then mailbox_host="$2"; shift; fi; shift ;;
        --mailbox-post=*) mailbox_post="${1#*=}"; shift ;;
        --mailbox-post) if [[ ! $2 == "" && ! $2 =~ ^-[^-] ]]; then mailbox_post="$2"; shift; fi; shift ;;
        --mailbox-web=*) mailbox_web="${1#*=}"; shift ;;
        --mailbox-web) if [[ ! $2 == "" && ! $2 =~ ^-[^-] ]]; then mailbox_web="$2"; shift; fi; shift ;;
        --phpmyadmin-version=*) phpmyadmin_version="${1#*=}"; shift ;;
        --phpmyadmin-version) if [[ ! $2 == "" && ! $2 =~ ^-[^-] ]]; then phpmyadmin_version="$2"; shift; fi; shift ;;
        --remote-user-root=*) remote_user_root="${1#*=}"; shift ;;
        --remote-user-root) if [[ ! $2 == "" && ! $2 =~ ^-[^-] ]]; then remote_user_root="$2"; shift; fi; shift ;;
        --remote-user-roundcube=*) remote_user_roundcube="${1#*=}"; shift ;;
        --remote-user-roundcube) if [[ ! $2 == "" && ! $2 =~ ^-[^-] ]]; then remote_user_roundcube="$2"; shift; fi; shift ;;
        --roundcube-version=*) roundcube_version="${1#*=}"; shift ;;
        --roundcube-version) if [[ ! $2 == "" && ! $2 =~ ^-[^-] ]]; then roundcube_version="$2"; shift; fi; shift ;;
        --subdomain-ispconfig=*) subdomain_ispconfig="${1#*=}"; shift ;;
        --subdomain-ispconfig) if [[ ! $2 == "" && ! $2 =~ ^-[^-] ]]; then subdomain_ispconfig="$2"; shift; fi; shift ;;
        --subdomain-phpmyadmin=*) subdomain_phpmyadmin="${1#*=}"; shift ;;
        --subdomain-phpmyadmin) if [[ ! $2 == "" && ! $2 =~ ^-[^-] ]]; then subdomain_phpmyadmin="$2"; shift; fi; shift ;;
        --subdomain-roundcube=*) subdomain_roundcube="${1#*=}"; shift ;;
        --subdomain-roundcube) if [[ ! $2 == "" && ! $2 =~ ^-[^-] ]]; then subdomain_roundcube="$2"; shift; fi; shift ;;
        --timezone=*) timezone="${1#*=}"; shift ;;
        --timezone) if [[ ! $2 == "" && ! $2 =~ ^-[^-] ]]; then timezone="$2"; shift; fi; shift ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done

set -- "${_new_arguments[@]}"

unset _new_arguments

# --- End.

if [ -n "$help" ];then
    cat <<'EOF'
Gak Pake Lama ISPConfig Autoinstaller Variation 1

Usage: gpl-ispconfig-variation1.sh [<domain>] [<ip_address>]

Avilable Options:
    --help|-h                   Show this help.
    --timezone                  Set timezone. Default: `Asia/Jakarta`.
    --phpmyadmin-version        Set PHPMyAdmin version. Default: `5.2.0`.
    --roundcube-version         Set Roundcube version. Default: `1.6.0`.
    --mailbox-admin             Mailbox for admin. Default: `admin`.
    --mailbox-host              Mailbox for hostmaster. Default: `hostmaster`.
    --mailbox-post              Mailbox for postmaster. Default: `postmaster`.
    --mailbox-web               Mailbox for webmaster. Default: `webmaster`.
    --digitalocean-token        Token to access Digitalocean API.
    --hostname                  Set the hostname. Default: `server1`.
    --remote-user-root          Username for ISPConfig remote user for general.
                                Default: `root`.
    --remote-user-roundcube     Username for ISPConfig remote user for mailbox.
                                Default: `roundcube`.
    --subdomain-ispconfig       Subdomain to ISPConfig. Default: `cp`.
                                Affect if argument <domain> exists.
    --subdomain-phpmyadmin      Subdomain to PHPMyAdmin. Default: `db`.
                                Affect if argument <domain> exists.
    --subdomain-roundcube       Subdomain to RoundCube. Default: `mail`.
                                Affect if argument <domain> exists.
    --autopopulate-ip-address   Fill the argument of <ip_address> automatically.
                                Affect if argument <domain> exists.
    --dkim-selector             Set value of DKIM. Default: `default`.
    --letsencrypt[=<dns-provider>]
                                Use letsencrypt to setup TLS/SSL for HTTPS.
                                Available value of <dns-provider>:
                                - `digitalocean`
EOF
exit 1
fi

# Common function.
red() { echo -ne "\e[91m"; echo -n "$@"; echo -e "\e[39m"; }
green() { echo -ne "\e[92m"; echo -n "$@"; echo -e "\e[39m"; }
yellow() { echo -ne "\e[93m"; echo -n "$@"; echo -e "\e[39m"; }
blue() { echo -ne "\e[94m"; echo -n "$@"; echo -e "\e[39m"; }
magenta() { echo -ne "\e[95m"; echo -n "$@"; echo -e "\e[39m"; }
x() { exit 1; }
e() { echo "$@"; }
__() { echo -n '    '; [ -n "$1" ] && echo "$@" || echo -n ; }
____() { echo; }

domain="$1"
ip_address="$2"
[ -n "$domain" ] && {
    if ! grep -P '(?=^.{5,254}$)(^(?:(?!\d+\.)[a-zA-Z0-9_\-]{1,63}\.?)+(?:[a-zA-Z]{2,})$)' <<< "$domain";then
        red "Argument <domain> has not valid characters."; x
    fi
}

# Default value.
[ -n "$timezone" ] || { timezone='Asia/Jakarta'; }
[ -n "$phpmyadmin_version" ] || { phpmyadmin_version='5.2.0'; }
[ -n "$roundcube_version" ] || { roundcube_version='1.6.0'; }
[ -n "$mailbox_admin" ] || { mailbox_admin='admin'; }
[ -n "$mailbox_host" ] || { mailbox_host='hostmaster'; }
[ -n "$mailbox_post" ] || { mailbox_post='postmaster'; }
[ -n "$mailbox_web" ] || { mailbox_web='webmaster'; }
[ -n "$hostname" ] || { hostname='server1'; }
[ -n "$remote_user_root" ] || { remote_user_root='root'; }
[ -n "$remote_user_roundcube" ] || { remote_user_roundcube='roundcube'; }
[ -n "$subdomain_ispconfig" ] || { subdomain_ispconfig='cp'; }
[ -n "$subdomain_phpmyadmin" ] || { subdomain_phpmyadmin='db'; }
[ -n "$subdomain_roundcube" ] || { subdomain_roundcube='mail'; }
[ -n "$dkim_selector" ] || { dkim_selector='default'; }
if [ -n "$domain" ];then
    fqdn="${hostname}.${domain}"
else
    fqdn="${hostname}.localhost"
fi

blue '######################################################################'
blue '#                                                                    #'
blue '# Gak Pake Lama ISPConfig Autoinstaller Variation 1                  #'
blue '#                                                                    #'
blue '######################################################################'
____

e Version 0.1.0
____

yellow User variable.
magenta 'domain="'${domain}'"'
magenta 'ip_address="'${ip_address}'"'
magenta 'digitalocean_token="'${digitalocean_token}'"'
magenta 'timezone="'$timezone'"'
magenta 'phpmyadmin_version="'$phpmyadmin_version'"'
magenta 'roundcube_version="'${roundcube_version}'"'
magenta 'mailbox_admin="'${mailbox_admin}'"'
magenta 'mailbox_host="'${mailbox_host}'"'
magenta 'mailbox_post="'${mailbox_post}'"'
magenta 'mailbox_web="'${mailbox_web}'"'
magenta 'hostname="'${hostname}'"'
magenta 'remote_user_root="'${remote_user_root}'"'
magenta 'remote_user_roundcube="'${remote_user_roundcube}'"'
magenta 'autopopulate_ip_address="'${autopopulate_ip_address}'"'
magenta 'subdomain_ispconfig="'${subdomain_ispconfig}'"'
magenta 'subdomain_phpmyadmin="'${subdomain_phpmyadmin}'"'
magenta 'subdomain_roundcube="'${subdomain_roundcube}'"'
magenta 'dkim_selector="'${dkim_selector}'"'
magenta 'letsencrypt="'${letsencrypt}'"'
____

NOW=$(date +%Y%m%d-%H%M%S)
PHP_VERSION=7.4
PHPMYADMIN_DB_NAME=phpmyadmin
ROUNDCUBE_DB_NAME=roundcubemail
PHPMYADMIN_DB_USER_HOST=localhost
ROUNDCUBE_DB_USER_HOST=localhost
ISPCONFIG_DB_USER_HOST=localhost
PHPMYADMIN_DB_USER=pma
ROUNDCUBE_DB_USER=roundcube
PHPMYADMIN_NGINX_CONFIG_FILE=phpmyadmin
ROUNDCUBE_NGINX_CONFIG_FILE=roundcube
ISPCONFIG_NGINX_CONFIG_FILE=ispconfig
PHPMYADMIN_SUBDOMAIN_LOCALHOST=phpmyadmin.localhost
ROUNDCUBE_SUBDOMAIN_LOCALHOST=roundcube.localhost
ISPCONFIG_SUBDOMAIN_LOCALHOST=ispconfig.localhost
POSTFIX_CONFIG_FILE=/etc/postfix/master.cf
MYSQL_ROOT_PASSWD=/root/.mysql-root-passwd.txt
MYSQL_ROOT_PASSWD_INI=/root/.mysql-root-passwd.ini
ISPCONFIG_INSTALL_DIR=/usr/local/ispconfig

yellow Define variable.
magenta 'PHP_VERSION="'$PHP_VERSION'"'
magenta 'PHPMYADMIN_DB_NAME="'$PHPMYADMIN_DB_NAME'"'
magenta 'ROUNDCUBE_DB_NAME="'$ROUNDCUBE_DB_NAME'"'
magenta 'PHPMYADMIN_DB_USER_HOST="'$PHPMYADMIN_DB_USER_HOST'"'
magenta 'ROUNDCUBE_DB_USER_HOST="'$ROUNDCUBE_DB_USER_HOST'"'
magenta 'ISPCONFIG_DB_USER_HOST="'$ISPCONFIG_DB_USER_HOST'"'
magenta 'PHPMYADMIN_DB_USER="'$PHPMYADMIN_DB_USER'"'
magenta 'ROUNDCUBE_DB_USER="'$ROUNDCUBE_DB_USER'"'
magenta 'PHPMYADMIN_NGINX_CONFIG_FILE="'$PHPMYADMIN_NGINX_CONFIG_FILE'"'
magenta 'ROUNDCUBE_NGINX_CONFIG_FILE="'$ROUNDCUBE_NGINX_CONFIG_FILE'"'
magenta 'ISPCONFIG_NGINX_CONFIG_FILE="'$ISPCONFIG_NGINX_CONFIG_FILE'"'
magenta 'PHPMYADMIN_SUBDOMAIN_LOCALHOST="'$PHPMYADMIN_SUBDOMAIN_LOCALHOST'"'
magenta 'ROUNDCUBE_SUBDOMAIN_LOCALHOST="'$ROUNDCUBE_SUBDOMAIN_LOCALHOST'"'
magenta 'ISPCONFIG_SUBDOMAIN_LOCALHOST="'$ISPCONFIG_SUBDOMAIN_LOCALHOST'"'
magenta 'POSTFIX_CONFIG_FILE="'$POSTFIX_CONFIG_FILE'"'
magenta 'MYSQL_ROOT_PASSWD="'$MYSQL_ROOT_PASSWD'"'
magenta 'MYSQL_ROOT_PASSWD_INI="'$MYSQL_ROOT_PASSWD_INI'"'
magenta 'ISPCONFIG_INSTALL_DIR="'$ISPCONFIG_INSTALL_DIR'"'
____

this_file=$(realpath "$0")
directory_this_file=$(dirname "$this_file")
parent_pid=$$

files_required=$(cat <<EOF
${directory_this_file}/gpl-ispconfig-variation1-lib.sh
${directory_this_file}/gpl-ispconfig-variation1-init.sh
${directory_this_file}/gpl-ispconfig-variation1-report.sh
${directory_this_file}/gpl-ispconfig-variation1-soap-remote-user.sh
${directory_this_file}/gpl-ispconfig-variation1-roundcube-plugin-ispconfig-integration.sh
${directory_this_file}/gpl-ispconfig-variation1-domain-register-with-dkim.sh
${directory_this_file}/gpl-ispconfig-variation1-mailbox.sh
${directory_this_file}/gpl-ispconfig-variation1-digitalocean.sh
${directory_this_file}/gpl-ispconfig-variation1-letsencrypt.sh
EOF
)
while IFS= read -r line; do
    [ -f "${line}" ] || {
        red File not found: "${line}"; x
    }
done <<< "$files_required"

source "${directory_this_file}/gpl-ispconfig-variation1-lib.sh"

. "${directory_this_file}/gpl-ispconfig-variation1-init.sh"

. "${directory_this_file}/gpl-ispconfig-variation1-soap-remote-user.sh"

. "${directory_this_file}/gpl-ispconfig-variation1-roundcube-plugin-ispconfig-integration.sh"

if [ -n "$domain" ];then
    . "${directory_this_file}/gpl-ispconfig-variation1-domain-register-with-dkim.sh"
    . "${directory_this_file}/gpl-ispconfig-variation1-mailbox.sh"
fi

if [[ -n "$domain" && -n "$digitalocean_token" ]];then
    if [[ -z "$ip_address" && -n "$autopopulate_ip_address" ]];then
        ip_address=$(wget -T 3 -t 1 -4qO- "http://ip1.dynupdate.no-ip.com/")
        [ -n "$ip_address" ] || { red "The Value of ip_address failed to autopopulate."; }
    fi
    if [ -n "$ip_address" ];then
        . "${directory_this_file}/gpl-ispconfig-variation1-digitalocean.sh"
    fi
fi

if [[ -n "$domain" && -n "$letsencrypt" ]];then
    if [[ ! "$letsencrypt" == 'digitalocean' ]];then
        red Currently not available letsencrypt self DNS resolver.;
    fi
    if [[ "$letsencrypt" == 'digitalocean' && -z "$digitalocean_token" ]];then
        red Lets encrypt require Digital Ocean API Token.;
    fi
    if [[ "$letsencrypt" == 'digitalocean' && -n "$digitalocean_token" ]];then
        . "${directory_this_file}/gpl-ispconfig-variation1-letsencrypt.sh"
    fi
fi

. "${directory_this_file}/gpl-ispconfig-variation1-report.sh"

yellow -- FINISH ------------------------------------------------------------
____

exit 0

parse-options.sh \
--without-end-options-double-dash \
--compact \
--clean \
--no-hash-bang \
--no-original-arguments \
--no-error-invalid-options \
--no-error-require-arguments << EOF | clip
FLAG=(
'--help|-h'
'--autopopulate-ip-address'
)
VALUE=(
--timezone
--phpmyadmin-version
--roundcube-version
--hostname
--remote-user-roundcube
--remote-user-root
--mailbox-admin
--mailbox-host
--mailbox-web
--mailbox-post
--digitalocean-token
--subdomain-ispconfig
--subdomain-phpmyadmin
--subdomain-roundcube
--dkim-selector
)
FLAG_VALUE=(
--letsencrypt
)
EOF
