#!/bin/bash

RCM_EXTENSION_VERSION=0.11.0-alpha.3

# Usage Functions.
usage() {
    cat << EOF
Usage: rcm-ispconfig-setup-mode-website-roundcube [command] [options]

Options:
   --dns-plugin *
        Select how to create the DNS record.
        Values available from command: rcm-plugin(list --interface=dns).
   --tls-plugin
        Select how to obtain TLS Certificate for https protocol.
        if the URL doesn't clearly contain https, it means it's using https.
        if left blank, it means the certificate will not be obtained or set in web server configuration.
        Values available from command: rcm-plugin(list --interface=tls).
   --domain *
        Domain name of the mail server.
   --url *
        Add Roundcube public domain. The value can be domain or URL.
        Value available from command: rcm-ispconfig-setup-mode-website-roundcube(helper suggest-url [--domain]), or other.

Global Options.
   --version
        Print version of this script.
   --help
        Show this help.

RCM Config:
   --no-timer

Dependency:
   rcm-ispconfig:$RCM_EXTENSION_VERSION
   rcm-dig-apt
   rcm-dig-has-address

Download:
   [rcm-ispconfig-setup-variation-bundle](https://github.com/ijortengab/ispconfig-autoinstaller/raw/master/rcm/ispconfig/rcm-ispconfig-setup-variation-bundle.sh)
   [rcm-ispconfig-setup-variation-mailbox](https://github.com/ijortengab/ispconfig-autoinstaller/raw/master/rcm/ispconfig/rcm-ispconfig-setup-variation-mailbox.sh)
   [rcm-nginx-plugin-ispconfig](https://github.com/ijortengab/ispconfig-autoinstaller/raw/master/rcm/nginx/rcm-nginx-plugin-ispconfig.sh)

Pre Prompt:
   rcm-plugin(init --interface=dns)
   rcm-plugin(init --interface=tls)
   rcm-plugin(add --interface=dns --name=manual --command=rcm-ispconfig --version=$RCM_EXTENSION_VERSION --temporary)
   rcm-plugin(add --interface=tls --name=manual --command=rcm-ispconfig --version=$RCM_EXTENSION_VERSION --temporary)

Post Prompt:
   rcm-plugin(execute --interface=dns --name=[--dns-plugin] --method=prompt)
   rcm-plugin(execute --interface=tls --name=[--tls-plugin] --method=prompt --ignore-fail-on-empty-name)

EOF
}

# Prevent scripts from being executed directly.
[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --bypass-validation-is-installed) bypass_validation_is_installed=1; shift ;;
        --dns-plugin=*) dns_plugin="${1#*=}"; shift ;;
        --dns-plugin) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then dns_plugin="$2"; shift; fi; shift ;;
        --domain=*) domain="${1#*=}"; shift ;;
        --domain) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then domain="$2"; shift; fi; shift ;;
        --tls-plugin=*) tls_plugin="${1#*=}"; shift ;;
        --tls-plugin) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then tls_plugin="$2"; shift; fi; shift ;;
        --url=*) url="${1#*=}"; shift ;;
        --url) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then url="$2"; shift; fi; shift ;;
        --) shift
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    *) _new_arguments+=("$1"); shift ;;
                esac
            done
            ;;
        --[^-]*) shift ;;
        helper)
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    *) _new_arguments+=("$1"); shift ;;
                esac
            done
            ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Command.
if [ -n "$1" ];then
    command=
    case "$1" in
        helper) command="$1"; shift ;;
    esac
    if [ -z "$command" ];then
        error Command unknown: '`'"$1"'`'.; x
    fi
fi

# Define variables and constants.
RCM_TLD_SPECIAL=${RCM_TLD_SPECIAL:=example test onion invalid local localhost alt}
SUBDOMAIN_ROUNDCUBE=${SUBDOMAIN_ROUNDCUBE:=mail}

PHP_FPM_USER=${PHP_FPM_USER:=ispconfig}
ISPCONFIG_FQDN_LOCALHOST=${ISPCONFIG_FQDN_LOCALHOST:=ispconfig.localhost}
ROUNDCUBE_FQDN_LOCALHOST=${ROUNDCUBE_FQDN_LOCALHOST:=roundcube.localhost}

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

# Functions.
ArrayDiff() {
    # Computes the difference of arrays.
    #
    # Globals:
    #   Modified: _return
    #
    # Arguments:
    #   1 = Parameter of the array to compare from.
    #   2 = Parameter of the array to compare against.
    #
    # Returns:
    #   None
    #
    # Example:
    #   ```
    #   my=("cherry" "manggo" "blackberry" "manggo" "blackberry")
    #   yours=("cherry" "blackberry")
    #   ArrayDiff my[@] yours[@]
    #   # Get result in variable `$_return`.
    #   # _return=("manggo" "manggo")
    #   ```
    local e
    local source=("${!1}")
    local reference=("${!2}")
    _return=()
    # inArray is alternative of ArraySearch.
    inArray () {
        local e match="$1"
        shift
        for e; do [[ "$e" == "$match" ]] && return 0; done
        return 1
    }
    if [[ "${#reference[@]}" -gt 0 ]];then
        for e in "${source[@]}";do
            if ! inArray "$e" "${reference[@]}";then
                _return+=("$e")
            fi
        done
    else
        _return=("${source[@]}")
    fi
}
Rcm_parse_url() {
    # Reset
    PHP_URL_SCHEME=
    PHP_URL_HOST=
    PHP_URL_PORT=
    PHP_URL_USER=
    PHP_URL_PASS=
    PHP_URL_PATH=
    PHP_URL_QUERY=
    PHP_URL_FRAGMENT=
    PHP_URL_SCHEME="$(echo "$1" | grep :// | sed -e's,^\(.*\)://.*,\1,g')"
    _PHP_URL_SCHEME_SLASH="${PHP_URL_SCHEME}://"
    _PHP_URL_SCHEME_REVERSE="$(echo ${1/${_PHP_URL_SCHEME_SLASH}/})"
    if grep -q '#' <<< "$_PHP_URL_SCHEME_REVERSE";then
        PHP_URL_FRAGMENT=$(echo $_PHP_URL_SCHEME_REVERSE | cut -d# -f2)
        _PHP_URL_SCHEME_REVERSE=$(echo $_PHP_URL_SCHEME_REVERSE | cut -d# -f1)
    fi
    if grep -q '\?' <<< "$_PHP_URL_SCHEME_REVERSE";then
        PHP_URL_QUERY=$(echo $_PHP_URL_SCHEME_REVERSE | cut -d? -f2)
        _PHP_URL_SCHEME_REVERSE=$(echo $_PHP_URL_SCHEME_REVERSE | cut -d? -f1)
    fi
    _PHP_URL_USER_PASS="$(echo $_PHP_URL_SCHEME_REVERSE | grep @ | cut -d@ -f1)"
    PHP_URL_PASS=`echo $_PHP_URL_USER_PASS | grep : | cut -d: -f2`
    if [ -n "$PHP_URL_PASS" ]; then
        PHP_URL_USER=`echo $_PHP_URL_USER_PASS | grep : | cut -d: -f1`
    else
        PHP_URL_USER=$_PHP_URL_USER_PASS
    fi
    _PHP_URL_HOST_PORT="$(echo ${_PHP_URL_SCHEME_REVERSE/$_PHP_URL_USER_PASS@/} | cut -d/ -f1)"
    PHP_URL_HOST="$(echo $_PHP_URL_HOST_PORT | sed -e 's,:.*,,g')"
    if grep -q -E ':[0-9]+$' <<< "$_PHP_URL_HOST_PORT";then
        PHP_URL_PORT="$(echo $_PHP_URL_HOST_PORT | sed -e 's,^.*:,:,g' -e 's,.*:\([0-9]*\).*,\1,g' -e 's,[^0-9],,g')"
    fi
    _PHP_URL_HOST_PORT_LENGTH=${#_PHP_URL_HOST_PORT}
    _LENGTH="$_PHP_URL_HOST_PORT_LENGTH"
    if [ -n "$_PHP_URL_USER_PASS" ];then
        _PHP_URL_USER_PASS_LENGTH=${#_PHP_URL_USER_PASS}
        _LENGTH=$((_LENGTH + 1 + _PHP_URL_USER_PASS_LENGTH))
    fi
    PHP_URL_PATH="${_PHP_URL_SCHEME_REVERSE:$_LENGTH}"

    # Debug
    # e '"$PHP_URL_SCHEME"' "$PHP_URL_SCHEME"
    # e '"$PHP_URL_HOST"' "$PHP_URL_HOST"
    # e '"$PHP_URL_PORT"' "$PHP_URL_PORT"
    # e '"$PHP_URL_USER"' "$PHP_URL_USER"
    # e '"$PHP_URL_PASS"' "$PHP_URL_PASS"
    # e '"$PHP_URL_PATH"' "$PHP_URL_PATH"
    # e '"$PHP_URL_QUERY"' "$PHP_URL_QUERY"
    # e '"$PHP_URL_FRAGMENT"' "$PHP_URL_FRAGMENT"
}
urlAlternative() {
    [[ $(type -t Rcm_parse_url) == function ]] || { error Function Rcm_parse_url not found.; x; }
    local url=$1 port=$2 path=$3
    local PHP_URL_SCHEME PHP_URL_USER PHP_URL_PASS PHP_URL_HOST PHP_URL_PORT PHP_URL_PATH
    local scheme
    Rcm_parse_url $url
    [ $port == - ] && port=
    [ -z "$port" ] && port="$PHP_URL_PORT"
    [ -z "$port" ] && port=8080
    [ -n "$PHP_URL_SCHEME" ] && scheme="$PHP_URL_SCHEME" || scheme=https
    echo "${scheme}://${PHP_URL_HOST}:${port}${path}"
}
command-helper() {
    local helper=$1; shift
    if [ "$helper" == do-nothing ];then
        return
    fi
    if [ -n "$helper" ];then
        if [[ $(type -t "helper-${helper}") == function ]];then
            helper-${helper} "$@"
            exit 0
        else
            error Helper unknown: '`'"$helper"'`'.; x
        fi
    fi
}
helper-suggest-url() {
    [[ $(type -t ArrayDiff) == function ]] || { error Function ArrayDiff not found.; x; }
    [[ $(type -t urlAlternative) == function ]] || { error Function urlAlternative not found.; x; }
    local PHP_URL_SCHEME PHP_URL_USER PHP_URL_PASS PHP_URL_HOST PHP_URL_PORT PHP_URL_PATH
    local domain=$1
    [ $domain == - ] && domain=
    [ -z "$domain" ] && return 0
    local array=("${SUBDOMAIN_ROUNDCUBE}.${domain}")
    for port in 8080 8081 8443; do
        array+=($(urlAlternative "$domain" "$port"))
        array+=($(urlAlternative "$domain" "$port" /roundcube))
        array+=($(urlAlternative "$domain" "$port" "/${SUBDOMAIN_ROUNDCUBE}"))
    done
    for each in "${array[@]}"; do
        echo "$each"
    done
}

# Execute command.
if [ -n "$command" ];then
    if [[ $(type -t "command-${command}") == function ]];then
        command-${command} "$@"
        exit 0
    else
        error Command unknown: '`'"$command"'`'.; x
    fi
fi

# ------------------------------------------------------------------------------

# Title.
title rcm-ispconfig-setup-mode-website-roundcube
____

# Dependency.

# Source: ISPConfigDebianOS::runPerfectSetup()
if [ -z "$bypass_validation_is_installed" ];then
    chapter Mengecek existing ISPConfig.
    path=/usr/local/ispconfig/server/lib/config.inc.php
    code 'path="'$path'"'
    if [ ! -f "$path" ]; then
        __ File '`'$path'`' not found.
        error The ISPConfig is not installed. Aborting.; x
    else
        __ File '`'$path'`' found.;
        __ Process is continue.
    fi
    ____
fi

# Functions.
ArraySearch() {
    local index match="$1"
    local source=("${!2}")
    for index in "${!source[@]}"; do
       if [[ "${source[$index]}" == "${match}" ]]; then
           _return=$index; return 0
       fi
    done
    return 1
}
backupFile() {
    local mode="$1"
    local oldpath="$2" i newpath
    local target_dir="$3"
    i=1
    dirname=$(dirname "$oldpath")
    basename=$(basename "$oldpath")
    if [ -n "$target_dir" ];then
        case "$target_dir" in
            parent) dirname=$(dirname "$dirname") ;;
            *) dirname="$target_dir"
        esac
    fi
    [ -d "$dirname" ] || { echo 'Directory is not exists.' >&2; return 1; }
    newpath="${dirname}/${basename}.${i}"
    if [ -f "$newpath" ]; then
        let i++
        newpath="${dirname}/${basename}.${i}"
        while [ -f "$newpath" ] ; do
            let i++
            newpath="${dirname}/${basename}.${i}"
        done
    fi
    case $mode in
        move)
            mv "$oldpath" "$newpath" ;;
        copy)
            local user=$(stat -c "%U" "$oldpath")
            local group=$(stat -c "%G" "$oldpath")
            cp "$oldpath" "$newpath"
            chown ${user}:${group} "$newpath"
    esac
}
fileMustExists() {
    # global used:
    # global modified:
    # function used: __, success, error, x
    if [ -f "$1" ];then
        __; green File '`'$(basename "$1")'`' ditemukan.; _.
    else
        __; red File '`'$(basename "$1")'`' tidak ditemukan.; x
    fi
}
isFileExists() {
    # global used:
    # global modified: found, notfound
    # function used: __
    found=
    notfound=
    if [ -f "$1" ];then
        __ File '`'$(basename "$1")'`' ditemukan.
        found=1
    else
        __ File '`'$(basename "$1")'`' tidak ditemukan.
        notfound=1
    fi
}
urlCompleteComponent() {
    local tld_special _url_port _tld _url_path_correct
    [[ $(type -t Rcm_parse_url) == function ]] || { error Function Rcm_parse_url not found.; x; }
    [[ $(type -t ArraySearch) == function ]] || { error Function ArraySearch not found.; x; }
    [[ -n "$url" ]] || { error Global variable url is not found or empty value.; x; }
    [[ -n "$RCM_TLD_SPECIAL" ]] || { error Global variable RCM_TLD_SPECIAL is not found or empty value.; x; }
    Rcm_parse_url "$url"
    if [ -z "$PHP_URL_HOST" ];then
        error Argument --url is not valid: '`'"$url"'`'.; x
    fi
    [ -n "$PHP_URL_SCHEME" ] && url_scheme="$PHP_URL_SCHEME" || url_scheme=https
    if [ -z "$PHP_URL_PORT" ];then
        case "$url_scheme" in
            http) url_port=80;;
            https) url_port=443;;
        esac
    else
        url_port="$PHP_URL_PORT"
    fi
    url_host="$PHP_URL_HOST"
    url_path="$PHP_URL_PATH"
    url_path_clean=
    url_path_clean_trailing=
    if [[ "$url_path" == '/' ]];then
        url_path=
    fi
    if [ -n "$url_path" ];then
        # Trim leading and trailing slash.
        url_path_clean=$(echo "$url_path" | sed -E 's|(^/+\|/+$)||g')
        url_path_clean_trailing=$(echo "$url_path" | sed -E 's|/+$||g')
        # Must leading with slash.
        # Karena akan digunakan pada nginx configuration.
        _url_path_correct="/${url_path_clean}"
        if [ ! "$url_path_clean_trailing" == "$_url_path_correct" ];then
            error "Argument --url-path not valid."; x
        fi
    fi
    _tld="${url_host##*.}"
    # Explode by space.
    read -ra tld_special -d '' <<< "$RCM_TLD_SPECIAL"
    is_tld_special=
    if ArraySearch "$_tld" tld_special[@];then
        # Paksa menjadi http.
        url_scheme=http
        if [ -z "$PHP_URL_PORT" ];then
            url_port=80
        fi
        is_tld_special=1
    fi
    _url_port=
    if [ -n "$url_port" ];then
        if [[ "$url_scheme" == https && "$url_port" == 443 ]];then
            _url_port=
        elif [[ "$url_scheme" == http && "$url_port" == 80 ]];then
            _url_port=
        else
            _url_port=":${url_port}"
        fi
    fi
    # Modify variable url, auto add scheme.
    # Modify variable url, auto trim trailing slash, auto add port.
    url="${url_scheme}://${url_host}${_url_port}${url_path_clean_trailing}"
}

# Require, validate, and populate value.
chapter Variable dump.
[ -n "$fast" ] && isfast=' --fast' || isfast=''
code 'ISPCONFIG_FQDN_LOCALHOST="'$ISPCONFIG_FQDN_LOCALHOST'"'
code 'ROUNDCUBE_FQDN_LOCALHOST="'$ROUNDCUBE_FQDN_LOCALHOST'"'

if [ -z "$dns_plugin" ];then
    error "Argument --dns-plugin required."; x
else
    dns_plugin_available=()
    while read line; do
        dns_plugin_available+=($line)
    done <<< `rcm-plugin list --interface=dns`
    if ! ArraySearch "$dns_plugin" dns_plugin_available[@];then
        error "Argument --dns-plugin not valid."; x
    fi
fi
code 'dns_plugin="'$dns_plugin'"'
if [ -n "$tls_plugin" ];then
    tls_plugin_available=()
    while read line; do
        tls_plugin_available+=($line)
    done <<< `rcm-plugin list --interface=tls`
    if ! ArraySearch "$tls_plugin" tls_plugin_available[@];then
        error "Argument --tls-plugin not valid."; x
    fi
fi
code 'tls_plugin="'$tls_plugin'"'
if [ -z "$domain" ];then
    error "Argument --domain required."; x
fi
code domain="$domain"
domain_length="${#domain}"
code 'domain_length="'$domain_length'"'

code url="$url"
urlCompleteComponent
if [ ! "${url_host:(-$domain_length):$domain_length}" == "$domain" ];then
    error Argument --url is not part of domain: '`'"$domain"'`'.; x
fi
code url="$url"
____

export RCM_DOMAIN="$domain"
INDENT+='    ' \
rcm-plugin $isfast execute --interface=dns --name="$dns_plugin" --method='is_domain_exists' \
    ; [ ! $? -eq 0 ] && x
____

chapter Prepare arguments.
prefix=$(getent passwd "$PHP_FPM_USER" | cut -d: -f6 )
root="$prefix/interface/web"
code root="$root"
____

chapter Mencari informasi PHP-FPM Version yang digunakan oleh ISPConfig.
__ Membuat file "${root}/.well-known/__getversion.php"
mkdir -p "${root}/.well-known"
cat << 'EOF' > "${root}/.well-known/__getversion.php"
<?php
echo PHP_VERSION;
EOF
__ Eksekusi file script.
__; magenta curl http://127.0.0.1/.well-known/__getversion.php -H '"'"Host: ${ISPCONFIG_FQDN_LOCALHOST}"'"'; _.
php_version=$(curl -Ss http://127.0.0.1/.well-known/__getversion.php -H "Host: ${ISPCONFIG_FQDN_LOCALHOST}")
__; magenta php_version="$php_version"; _.
if [ -z "$php_version" ];then
    error PHP-FPM version tidak ditemukan; x
fi
__ Menghapus file "${root}/.well-known/__getversion.php"
rm "${root}/.well-known/__getversion.php"
rmdir "${root}/.well-known" --ignore-fail-on-non-empty
____

chapter Perbaikan variable '`'php_version'`'.
__; magenta php_version="$php_version"; _.
major=$(sed -E 's,^([0-9]+)\.([0-9]+)\.([0-9]+)$,\1,' <<< "$php_version")
minor=$(sed -E 's,^([0-9]+)\.([0-9]+)\.([0-9]+)$,\2,' <<< "$php_version")
php_version="${major}.${minor}"
__; magenta php_version="$php_version"; _.
____

# Obtain Certificate.
# We hope the variable environment of NGINX_SSL_CERTIFICATE and
# NGINX_SSL_CERTIFICATE_KEY will be defined.
if [ -n "$tls_plugin" ];then
    [ -z "$tempfile" ] && tempfile=$(mktemp -p /dev/shm -t rcm-ispconfig-setup-mode-init.XXXXXX)
    export RCM_FQDN="$url_host"
    INDENT+='    ' \
    rcm-plugin $isfast execute --interface=tls --name="$tls_plugin" \
        --method='obtain_certificate' \
        --output-file="$tempfile" \
        ; [ ! $? -eq 0 ] && x
    if [ -s "$tempfile" ];then
        # Tidak gunakan export, cukup gunakan source karena untuk kebutuhan
        # internal script ini.
        source "$tempfile"
        while IFS= read -r line; do
            code "$line"
        done < "$tempfile"
        ____
    fi
fi

# todo, seharusnya bisa install ispconfig tanpa tls. sementara anggap lah
# wajib.
# Populate value.
# If not set in argument, try load from environment.
[ -z "$tls_certificate" ] && tls_certificate="$TLS_CERTIFICATE"
[ -z "$tls_certificate_key" ] && tls_certificate_key="$TLS_CERTIFICATE_KEY"

INDENT+="    " \
rcm-ispconfig-setup-wrapper-nginx-virtual-host-autocreate-php-multiple-root $isfast \
    --project=roundcube \
    --php-version="$php_version" \
    --url="$url" \
    --tls-certificate="$tls_certificate" \
    --tls-certificate-key="$tls_certificate_key" \
    ; [ ! $? -eq 0 ] && x

php=$(cat <<'EOF'
$mode = $_SERVER['argv'][1];
switch ($mode) {
    case 'is_different':
    case 'save':
        # Populate variable $is_different.
        $file = $_SERVER['argv'][2];
        $reference = unserialize($_SERVER['argv'][3]);
        include($file);
        $config = isset($config) ? $config : [];
        $is_different = !empty(array_diff_assoc(array_map('serialize',$reference), array_map('serialize',$config)));
        break;
}
switch ($mode) {
    case 'is_different':
        $is_different ? exit(0) : exit(1);
        break;
    case 'save':
        if (!$is_different) {
            exit(0);
        }
        $contents = file_get_contents($file);
        $need_edit = array_diff_assoc($reference, $config);
        $new_lines = [];
        foreach ($need_edit as $key => $value) {
            $new_line = "__PARAMETER__[__KEY__] = __VALUE__; # managed by RCM";
            // Jika indexed array dan hanya satu , maka buat one line.
            if (is_array($value) && array_key_exists(0, $value) && count($value) === 1) {
                $new_line = str_replace(['__PARAMETER__','__KEY__','__VALUE__'],['$config', var_export($key, true), "['".$value[0]."']"], $new_line);
            }
            else {
                $new_line = str_replace(['__PARAMETER__','__KEY__','__VALUE__'],['$config', var_export($key, true), var_export($value, true)], $new_line);
            }
            $is_one_line = preg_match('/\n/', $new_line) ? false : true;
            $find_existing = "__PARAMETER__[__KEY__] = __VALUE__; # managed by RCM";
            $find_existing = str_replace(['__PARAMETER__','__KEY__'],['$config', var_export($key, true)], $find_existing);
            $find_existing = preg_quote($find_existing);
            $find_existing = str_replace('__VALUE__', '.*', $find_existing);
            $find_existing = '/\s*'.$find_existing.'/';
            if ($is_one_line && preg_match_all($find_existing, $contents, $matches, PREG_PATTERN_ORDER)) {
                $contents = str_replace($matches[0], '', $contents);
            }
            $new_lines[] = $new_line;
        }
        if (substr($contents, -1) != "\n") {
            $contents .= "\n";
        }
        $contents .= implode("\n", $new_lines);
        $contents .= "\n";
        file_put_contents($file, $contents);
        break;
}
EOF
)

# @todo, rename parameter.
chapter Roundcube Virtual Host.
url_roundcube="$url"
roundcube_url_host="$url_host"
code 'url_roundcube="'$url_roundcube'"'
code 'roundcube_url_host="'$roundcube_url_host'"'
____

chapter Prepare arguments.
nginx_user=
conf_nginx=`command -v nginx > /dev/null && command -v nginx > /dev/null && nginx -V 2>&1 | grep -o -P -- '--conf-path=\K(\S+)'`
if [ -f "$conf_nginx" ];then
    nginx_user=`grep -o -P '^user\s+\K([^;]+)' "$conf_nginx"`
fi
code 'nginx_user="'$nginx_user'"'
if [ -z "$nginx_user" ];then
    error "Variable \$nginx_user failed to populate."; x
fi
nginx_user_home=$(getent passwd "$nginx_user" | cut -d: -f6 )
php_fpm_user="$nginx_user"
code 'php_fpm_user="'$php_fpm_user'"'
prefix="$nginx_user_home"

project_container="$ROUNDCUBE_FQDN_LOCALHOST"
code 'project_container="'$project_container'"'
root="$prefix/${project_container}/web"
root_source=$(realpath "$root")
if [ $(basename "$root_source") == "public_html" ];then
    root_source=$(dirname "$root_source")
else
    error "Direktori public_html tidak ditemukan"; x
fi
php_project_name=www
code 'php_project_name="'$php_project_name'"'
code root="$root"
code root_source="$root_source"
____

# https://github.com/roundcube/roundcubemail/blob/master/config/defaults.inc.php
# https://github.com/roundcube/roundcubemail/wiki/Configuration:-Multi-Domain-Setup
chapter Mengecek file konfigurasi RoundCube.
filename="${roundcube_url_host}.inc.php"
path="${root_source}/config/${roundcube_url_host}.inc.php"
isFileExists "$path"
____

if [ -n "$notfound" ];then
    chapter Membuat RoundCube config file: '`'$filename'`'.
    code sudo -u '"'$php_fpm_user'"' touch '"'$path'"'
    sudo -u "$php_fpm_user" touch "$path"
    cat <<'EOF' > "$path"
<?php

// Website: __URL_ROUNDCUBE__
$config['username_domain'] = '__DOMAIN__'; # managed by RCM
EOF
    fileMustExists "$path"
    sed -i "s|__URL_ROUNDCUBE__|${url_roundcube}|g" "$path"
    sed -i "s|__DOMAIN__|${domain}|g" "$path"
    ____
fi
reference="$(php -r "echo serialize([
    'username_domain' => '${domain}',
]);")"
is_different=
if php -r "$php" is_different "$path" "$reference";then
    is_different=1
    __ Diperlukan modifikasi file '`'$filename'`'.
else
    __ File '`'$filename'`' tidak ada perubahan.
fi
____

if [ -n "$is_different" ];then
    chapter Memodifikasi file '`'$filename'`'.
    __ Backup file "$path"
    backupFile copy "$path"
    php -r "$php" save "$path" "$reference"
    if php -r "$php" is_different "$path" "$reference";then
        __; red Modifikasi file '`'$filename'`' gagal.; x
    else
        __; green Modifikasi file '`'$filename'`' berhasil.; _.
    fi
    ____
fi

chapter Saving URL information.
path=/usr/local/share/roundcube/domain/$url_host
code mkdir -p "$path"
mkdir -p "$path"
path=/usr/local/share/roundcube/domain/$url_host/website
cat << EOF >> "$path"
URL_ROUNDCUBE=$url
EOF
[ -f "$path" ] || fileMustExists "$path"
____

chapter Finish
____

exit 0

# parse-options.sh \
# --with-end-options-double-dash \
# --with-end-options-specific-operand \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# --bypass-validation-is-installed
# )
# VALUE=(
# --domain
# --url
# --dns-plugin
# --tls-plugin
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# CSV=(
# )
# OPERAND=(
# helper
# )
# EOF
# clear
