#!/bin/bash

RCM_EXTENSION_VERSION=0.11.0-alpha.8

# Usage Functions.
usage() {
    cat << EOF
Usage: rcm-ispconfig-control-manage-client [command] [options]
       rcm-ispconfig-control-manage-client get-client-id --username=<username>

Available commands: get-client-id.

Options:
   --username *
        Set the username.
   --email *
        Set the email.
   --password
        Set the password.
        Leave blank to autogenerate password.
   --
        Every arguments after double dash will pass to \`rcm-php-ispconfig soap client_add\` command.

Other Options:
   --ispconfig-soap-exists-sure
        By pass test connect to the SOAP server.
   --get-client-id
        Print client_id to STDOUT.

Options for command get-client-id:
   --username *
        Set the username.

Global Options:
   --version
        Print version of this script.
   --help
        Show this help.

Dependency:
   pwgen
   rcm-php-ispconfig:$RCM_EXTENSION_VERSION

Download:
   [rcm-php-ispconfig](https://github.com/ijortengab/ispconfig-autoinstaller/raw/master/rcm/php/rcm-php-ispconfig.php)
EOF
}

# Prevent scripts from being executed directly.
[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh._new_arguments=()
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --email=*) email="${1#*=}"; shift ;;
        --email) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then email="$2"; shift; fi; shift ;;
        --get-client-id) get_client_id=1; shift ;;
        --ispconfig-soap-exists-sure) ispconfig_soap_exists_sure=1; shift ;;
        --password=*) password="${1#*=}"; shift ;;
        --password) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then password="$2"; shift; fi; shift ;;
        --username=*) username="${1#*=}"; shift ;;
        --username) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then username="$2"; shift; fi; shift ;;
        --) shift
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    *) _new_arguments+=("$1"); shift ;;
                esac
            done
            ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Define variables and constants.

# Command.
if [ -n "$1" ];then
    case "$1" in
        get-client-id) command="$1"; shift ;;
    esac
fi

# Functions.
resolve_relative_path() {
    if [ -d "$1" ];then
        cd "$1" || return 1
        pwd
    elif [ -e "$1" ];then
        if [ ! "${1%/*}" = "$1" ]; then
            cd "${1%/*}" || return 1
        fi
        echo "$(pwd)/${1##*/}"
    else
        return 1
    fi
}
userInputBooleanDefaultYes() {
    __;  _, '['; yellow Enter; _, ']'; _, ' '; yellow Y; _, 'es and continue.'; _.
    __;  _, '['; yellow Esc; _, ']'; _, ' '; yellow N; _, 'o and skip.'; _.
    boolean=
    while true; do
        __; read -rsn 1 -p "Select: " char
        if [ -z "$char" ];then
            char=y
        fi
        case $char in
            y|Y) echo "$char"; boolean=1; break;;
            n|N) echo "$char"; break ;;
            $'\33') echo "n"; break ;;
            *) echo
        esac
    done
}

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

# Functions before execute command.
command-get-client-id() {
    # global $username
    title rcm-ispconfig-control-manage-client get-client-id
    ____

    if [ -z "$username" ];then
        error "Argument --username required."; x
    fi
    local tempfile=$(mktemp -p /dev/shm -t rcm-ispconfig-control-manage-client.XXXXXX)
    code rcm-php-ispconfig soap client_get_by_username '"'$username'"'
    rcm-php-ispconfig soap client_get_by_username "$username" 2>&1 &> "$tempfile"
    local exit_code=$?
    if [ $exit_code -eq 0 ];then
        client_id=$(rcm-php-ispconfig echo [client_id] < "$tempfile")
        echo $client_id
    else
        while IFS= read line; do e "$line"; _.; done < "$tempfile"
    fi
    rm "$tempfile"
    ____
}

# Execute command.
if [[ -n "$command" && $(type -t "command-${command}") == function ]];then
    command-${command} "$@"
    exit 0
fi

# ------------------------------------------------------------------------------

# Title.
title rcm-ispconfig-control-manage-client
____

# Dependency.

# Functions.
websiteCredentialIspconfig() {
    # global $username
    # global modified $password
    [ -n "$username" ] || { error Variable username is required; x; }
    local path="/usr/local/share/ispconfig/credential/client/${username}"
    local dirname="/usr/local/share/ispconfig/credential/client"
    __; magenta 'path="'$path'"'; _.
    if [ -z "$password" ];then
        password=$(pwgen 9 -1vA0B)
    fi
    if [ -f "$path" ];then
        local _password=$(<"$path")
        if [[ ! "$_password" == "$password" ]];then
            echo "$password" > "$path"
        fi
    else
        mkdir -p "$dirname"
        echo "$password" > "$path"
        chmod 0500 "$dirname"
        chmod 0400 "$path"
    fi
}
isExists() {
    # global $username, $tempfile
    # global modified $client_id
    [ -n "$username" ] || { error Variable username is required; x; }
    [ -n "$tempfile" ] || { error Variable tempfile is required; x; }

    code rcm-php-ispconfig soap client_get_by_username '"'$username'"'
    rcm-php-ispconfig soap client_get_by_username "$username" 2>&1 &> "$tempfile"
    local exit_code=$?
    if [ $exit_code -eq 0 ];then
        client_id=$(rcm-php-ispconfig echo [client_id] < "$tempfile")
        __; magenta client_id=$client_id; _.
    else
        while IFS= read line; do e "$line"; _.; done < "$tempfile"
    fi
    return $exit_code
}
create() {
    # global $username, $email, $tempfile
    # global modified $client_id
    [ -n "$username" ] || { error Variable username is required; x; }
    [ -n "$email" ] || { error Variable email is required; x; }
    [ -n "$tempfile" ] || { error Variable tempfile is required; x; }
    websiteCredentialIspconfig
    __; magenta 'password="'$password'"'; _.
    code rcm-php-ispconfig soap client_add '"'$username'"' --email='"'$email'"' --username='"'$username'"' --password='"'$password'"' "$@"
    rcm-php-ispconfig soap client_add --email="$email" --username="$username" --password="$password" "$@" 2>&1 &> "$tempfile"
    local exit_code=$?
    if [ $exit_code -eq 0 ];then
        client_id=$(cat "$tempfile" | rcm-php-ispconfig echo)
        __; magenta client_id=$client_id; _.
    else
        while IFS= read line; do e "$line"; _.; done < "$tempfile"
    fi
    return $exit_code
}

# Requirement, validate, and populate value.
chapter Variable dump.
if [ -z "$username" ];then
    error "Argument --username required."; x
fi
code 'username="'$username'"'
code 'password="'$password'"'
if [ -z "$email" ];then
    error "Argument --email required."; x
fi
code 'email="'$email'"'
code 'ispconfig_soap_exists_sure="'$ispconfig_soap_exists_sure'"'
tempfile=
____

if [ -z "$ispconfig_soap_exists_sure" ];then
    chapter Test koneksi SOAP.
    code rcm-php-ispconfig soap login
    if [ -z "$tempfile" ];then
        tempfile=$(mktemp -p /dev/shm -t rcm-ispconfig-control-manage-client.XXXXXX)
    fi
    if rcm-php-ispconfig soap login 2> "$tempfile";then
        while IFS= read line; do e "$line"; _.; done < "$tempfile"
        __ Login berhasil.
    else
        rm "$tempfile"
        error Login gagal; x
    fi
    ____
fi

chapter Autocreate client '`'$username'`' di Module Client ISPConfig.
if [ -z "$tempfile" ];then
    tempfile=$(mktemp -p /dev/shm -t rcm-ispconfig-control-manage-client.XXXXXX)
fi
if isExists;then
    __ Client '`'$username'`' telah terdaftar di ISPConfig.
elif create "$@";then
    success Client '`'$username'`' berhasil terdaftar di ISPConfig.
else
    error Client '`'$username'`' gagal terdaftar di ISPConfig.; x
fi
____

# Bedanya command get-client-id dengan --get-client-id
# Command get-client-id jika tidak exists, maka null.
# Jika option --get-client-id, maka jika tidak exists, akan dibuat dulu.
if [ -n "$get_client_id" ];then
    echo "$client_id"
fi

[ -n "$tempfile" ] && rm "$tempfile"

exit 0

# parse-options.sh \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# --ispconfig-soap-exists-sure
# --get-client-id
# )
# VALUE=(
# --username
# --password
# --email
# )
# CSV=(
# )
# EOF
# clear
