#!/bin/bash

RCM_EXTENSION_VERSION=0.10.0-alpha.6

# Usage Functions.
usage() {
    cat << EOF
Usage: rcm-ispconfig-setup-smtpd-certificate [options]

Options:
    --tls-certificate *
        TLS Certificate.
        Populate value from variable TLS_CERTIFICATE.
    --tls-certificate-key *
        TLS Certificate.
        Populate value from variable TLS_CERTIFICATE_KEY.

Global Options:
   --version
        Print version of this script.
   --help
        Show this help.

Environment Variables:
   POSTFIX_CONFIG_DIR
        Default to $POSTFIX_CONFIG_DIR
EOF
}

# Prevent scripts from being executed directly.
[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh.
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --tls-certificate-key=*) tls_certificate_key="${1#*=}"; shift ;;
        --tls-certificate-key) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then tls_certificate_key="$2"; shift; fi; shift ;;
        --tls-certificate=*) tls_certificate="${1#*=}"; shift ;;
        --tls-certificate) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then tls_certificate="$2"; shift; fi; shift ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Define variables and constants.
POSTFIX_CONFIG_DIR=${POSTFIX_CONFIG_DIR:=/etc/postfix}

# Help and Version.
[ -n "$help" ] && { usage; exit 1; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

# Title.
title rcm-ispconfig-setup-smtpd-certificate
____

# Dependency.
while IFS= read -r line; do
    [[ -z "$line" ]] || command -v `cut -d: -f1 <<< "${line}"` >/dev/null || { error Unable to proceed, command not found: '`'`cut -d: -f1 <<< "${line}"`'`'.; x; }
done <<< `usage 2>/dev/null | sed -n '/^Dependency:/,$p' | sed -n '2,/^\s*$/p' | sed 's/^ *//g'`

# Functions.
backupFile() {
    local mode="$1"
    local oldpath="$2" i newpath
    local target_dir="$3"
    i=1
    dirname=$(dirname "$oldpath")
    basename=$(basename "$oldpath")
    if [ -n "$target_dir" ];then
        case "$target_dir" in
            parent) dirname=$(dirname "$dirname") ;;
            *) dirname="$target_dir"
        esac
    fi
    [ -d "$dirname" ] || { echo 'Directory is not exists.' >&2; return 1; }
    newpath="${dirname}/${basename}.${i}"
    if [ -f "$newpath" ]; then
        let i++
        newpath="${dirname}/${basename}.${i}"
        while [ -f "$newpath" ] ; do
            let i++
            newpath="${dirname}/${basename}.${i}"
        done
    fi
    case $mode in
        move)
            mv "$oldpath" "$newpath" ;;
        copy)
            local user=$(stat -c "%U" "$oldpath")
            local group=$(stat -c "%G" "$oldpath")
            cp "$oldpath" "$newpath"
            chown ${user}:${group} "$newpath"
    esac
}
backupDir() {
    local oldpath="$1" i newpath
    # Trim trailing slash.
    oldpath=$(echo "$oldpath" | sed -E 's|/+$||g')
    i=1
    newpath="${oldpath}.${i}"
    if [ -e "$newpath" ]; then
        let i++
        newpath="${oldpath}.${i}"
        while [ -e "$newpath" ] ; do
            let i++
            newpath="${oldpath}.${i}"
        done
    fi
    mv "$oldpath" "$newpath"
}
link_symbolic() {
    local source="$1"
    local target="$2"
    local sudo="$3"
    local source_mode="$4"
    local create
    [ "$sudo" == - ] && sudo=
    [ "$source_mode" == absolute ] || source_mode=
    [ -e "$source" ] || { error Source not exist: $source.; x; }
    [ -f "$source" ] || { error Source exists but not file: $source.; x; }
    [ -n "$target" ] || { error Target not defined.; x; }
    [[ $(type -t backupFile) == function ]] || { error Function backupFile not found.; x; }
    [[ $(type -t backupDir) == function ]] || { error Function backupDir not found.; x; }
    chapter Membuat symbolic link.
    __ source: '`'$source'`'
    __ target: '`'$target'`'
    if [ -f "$target" ];then
        if [ -h "$target" ];then
            __ Path target saat ini sudah merupakan file symbolic link: '`'$target'`'
            local _readlink=$(readlink "$target")
            __; magenta readlink "$target"; _.
            _ $_readlink; _.
            if [[ "$_readlink" =~ ^[^/\.] ]];then
                local target_parent=$(dirname "$target")
                local _dereference="${target_parent}/${_readlink}"
            elif [[ "$_readlink" =~ ^[\.] ]];then
                local target_parent=$(dirname "$target")
                local _dereference="${target_parent}/${_readlink}"
                _dereference=$(realpath -s "$_dereference")
            else
                _dereference="$_readlink"
            fi
            __; _, Mengecek apakah link merujuk ke '`'$source'`':' '
            if [[ "$source" == "$_dereference" ]];then
                _, merujuk.; _.
            else
                _, tidak merujuk.; _.
                __ Melakukan backup.
                backupFile move "$target"
                create=1
            fi
        else
            __ Melakukan backup regular file: '`'"$target"'`'.
            backupFile move "$target"
            create=1
        fi
    elif [ -d "$target" ];then
        __ Melakukan backup direktori: '`'"$target"'`'.
        backupDir "$target"
        create=1
    else
        create=1
    fi
    if [ -n "$create" ];then
        __ Membuat symbolic link: '`'$target'`'.
        local target_parent=$(dirname "$target")
        code mkdir -p "$target_parent"
        mkdir -p "$target_parent"
        if [ -z "$source_mode" ];then
            source=$(realpath -s --relative-to="$target_parent" "$source")
        fi
        if [ -n "$sudo" ];then
            code sudo -u '"'$sudo'"' ln -s '"'$source'"' '"'$target'"'
            sudo -u "$sudo" ln -s "$source" "$target"
        else
            code ln -s '"'$source'"' '"'$target'"'
            ln -s "$source" "$target"
        fi
        if [ $? -eq 0 ];then
            __; green Symbolic link berhasil dibuat.; _.
        else
            __; red Symbolic link gagal dibuat.; x
        fi
    fi
    ____
}
fileMustExists() {
    # global used:
    # global modified:
    # function used: __, success, error, x
    if [ -f "$1" ];then
        __; green File '`'$(basename "$1")'`' ditemukan.; _.
    else
        __; red File '`'$(basename "$1")'`' tidak ditemukan.; x
    fi
}
verifyKey() {
    local key=$1
    local output=$2
    case "$key" in
        smtpd_tls_cert_file)
            prefer_parameter="prefer_${key}"
            if [[ "$output" == "${key} = ${!prefer_parameter}" ]];then
                return 0
            fi
            ;;
        smtpd_tls_key_file)
            prefer_parameter="prefer_${key}"
            if [[ "$output" == "${key} = ${!prefer_parameter}" ]];then
                return 0
            fi
            ;;
    esac
    return 1
}

# Require, validate, and populate value.
chapter Variable dump.
[ -n "$fast" ] && isfast=' --fast' || isfast=''
# If not set in argument, try load from environment.
[ -z "$tls_certificate" ] && tls_certificate="$TLS_CERTIFICATE"
[ -z "$tls_certificate_key" ] && tls_certificate_key="$TLS_CERTIFICATE_KEY"
if [ -z "$tls_certificate" ];then
    error "Argument --tls-certificate or variable TLS_CERTIFICATE required."; x
fi
code tls_certificate="$tls_certificate"
if [ -z "$tls_certificate_key" ];then
    error "Argument --tls-certificate-key or variable TLS_CERTIFICATE_KEY required."; x
fi
code tls_certificate_key="$tls_certificate_key"
[ -f "$tls_certificate" ] || fileMustExists "$tls_certificate"
[ -f "$tls_certificate_key" ] || fileMustExists "$tls_certificate_key"
smtpd_tls_cert_file=$(postconf -n smtpd_tls_cert_file | grep -o -P '^smtpd_tls_cert_file\s+=\s+\K([^;]+)')
smtpd_tls_key_file=$(postconf -n smtpd_tls_key_file | grep -o -P '^smtpd_tls_key_file\s+=\s+\K([^;]+)')
code smtpd_tls_cert_file="$smtpd_tls_cert_file"
code smtpd_tls_key_file="$smtpd_tls_key_file"
prefer_smtpd_tls_cert_file="${POSTFIX_CONFIG_DIR}/smtpd.cert"
prefer_smtpd_tls_key_file="${POSTFIX_CONFIG_DIR}/smtpd.key"
code prefer_smtpd_tls_cert_file="$prefer_smtpd_tls_cert_file"
code prefer_smtpd_tls_key_file="$prefer_smtpd_tls_key_file"
____

link_symbolic "$tls_certificate" "$prefer_smtpd_tls_cert_file" - absolute
link_symbolic "$tls_certificate_key" "$prefer_smtpd_tls_key_file" - absolute

tempfile_error=$(mktemp -p /dev/shm -t rcm-ispconfig-setup-smtpd-certificate.XXXXXX)
tempfile_output=$(mktemp -p /dev/shm -t rcm-ispconfig-setup-smtpd-certificate.XXXXXX)

for key in smtpd_tls_cert_file smtpd_tls_key_file; do
    chapter Memastikan key '`'$key'`' enabled.
    postconf -n $key 2> $tempfile_error > $tempfile_output
    error="$(<"$tempfile_error")"
    if [ -n "$error" ];then
        error "$error"; rm $tempfile_error; rm $tempfile_output; x
    fi
    output="$(<"$tempfile_output")"
    found=
    if [ -n "$output" ];then
        __ Key ditemukan.
        e "$output"; _.
        __ Verifikasi.
        if verifyKey "$key" "$output";then
            found=1
            __ Key ditemukan, dan value cocok.
        else
            __ Key ditemukan, namun value tidak cocok.
            __ Disable and create new one.
            code "postconf -# ${key}"
            postconf -# $key
        fi
    fi
    if [ -z "$found" ];then
        __ Set value of key '`'$key'`'
        prefer_parameter="prefer_${key}"
        postconf "${key}=${!prefer_parameter}"
        __ Verifikasi.
        if verifyKey "$key" "$(postconf -n $key)";then
            __ Verifikasi berhasil.
            restart=1
        else
            error Verifikasi gagal.; rm $tempfile_error; rm $tempfile_output; x
        fi
    fi
    ____
done

if [ -n "$restart" ];then
    chapter Restart Postfix
    code systemctl restart postfix
    systemctl restart postfix
    ____
fi

rm $tempfile_error
rm $tempfile_output

exit 0

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# )
# VALUE=(
# --tls-certificate
# --tls-certificate-key
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# CSV=(
# )
# EOF
# clear
