#!/bin/bash

RCM_EXTENSION_VERSION=0.10.0-alpha.6

# Usage Functions.
usage() {
    cat << EOF
Usage: rcm-dovecot-multiple-certificate-ispconfig [options]

Options:
   --fqdn *
        Fully Qualified Domain Name of the certificate, for example: \`server1.example.org\`.
    --tls-certificate *
        TLS Certificate.
        Populate value from variable TLS_CERTIFICATE.
    --tls-certificate-key *
        TLS Certificate.
        Populate value from variable TLS_CERTIFICATE_KEY.

Global Options:
   --version
        Print version of this script.
   --help
        Show this help.

Environment Variables:
   MAILBOX_HOST
        Default to $MAILBOX_HOST
   DOVECOT_CONFIG_DIR
        Default to $DOVECOT_CONFIG_DIR
   DOVECOT_CONFIG_FILE_ISPCONFIG
        Default to $DOVECOT_CONFIG_FILE_ISPCONFIG

Dependency:
   rcm-dovecot-multiple-certificate
EOF
}

# Prevent scripts from being executed directly.
[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh.
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --fqdn=*) fqdn="${1#*=}"; shift ;;
        --fqdn) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then fqdn="$2"; shift; fi; shift ;;
        --tls-certificate-key=*) tls_certificate_key="${1#*=}"; shift ;;
        --tls-certificate-key) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then tls_certificate_key="$2"; shift; fi; shift ;;
        --tls-certificate=*) tls_certificate="${1#*=}"; shift ;;
        --tls-certificate) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then tls_certificate="$2"; shift; fi; shift ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Define variables and constants.
DOVECOT_CONFIG_DIR=${DOVECOT_CONFIG_DIR:=/etc/dovecot}
DOVECOT_CONFIG_FILE_ISPCONFIG=${DOVECOT_CONFIG_FILE_ISPCONFIG:=${DOVECOT_CONFIG_DIR}/conf.d/99-ispconfig-custom-config.conf}
MAILBOX_HOST=${MAILBOX_HOST:=hostmaster}

# Help and Version.
[ -n "$help" ] && { usage; exit 1; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

# Title.
title rcm-dovecot-multiple-certificate-ispconfig
____

# Dependency.
while IFS= read -r line; do
    [[ -z "$line" ]] || command -v `cut -d: -f1 <<< "${line}"` >/dev/null || { error Unable to proceed, command not found: '`'`cut -d: -f1 <<< "${line}"`'`'.; x; }
done <<< `usage 2>/dev/null | sed -n '/^Dependency:/,$p' | sed -n '2,/^\s*$/p' | sed 's/^ *//g'`

# Functions.
isDirExists() {
    # global used:
    # global modified: found, notfound
    # function used: __
    found=
    notfound=
    if [ -d "$1" ];then
        __ Direktori '`'$(basename "$1")'`' ditemukan.
        found=1
    else
        __ Direktori '`'$(basename "$1")'`' tidak ditemukan.
        notfound=1
    fi
}

# Require, validate, and populate value.
chapter Variable dump.
[ -n "$fast" ] && isfast=' --fast' || isfast=''
code 'MAILBOX_HOST="'$MAILBOX_HOST'"'
code 'DOVECOT_CONFIG_DIR="'$DOVECOT_CONFIG_DIR'"'
code 'DOVECOT_CONFIG_FILE_ISPCONFIG="'$DOVECOT_CONFIG_FILE_ISPCONFIG'"'
if [ -z "$fqdn" ];then
    error "Argument --fqdn required."; x
fi
code 'fqdn="'$fqdn'"'
# If not set in argument, try load from environment.
[ -z "$tls_certificate" ] && tls_certificate="$TLS_CERTIFICATE"
[ -z "$tls_certificate_key" ] && tls_certificate_key="$TLS_CERTIFICATE_KEY"
if [ -z "$tls_certificate" ];then
    error "Argument --tls-certificate or variable TLS_CERTIFICATE required."; x
fi
code tls_certificate="$tls_certificate"
if [ -z "$tls_certificate_key" ];then
    error "Argument --tls-certificate-key or variable TLS_CERTIFICATE_KEY required."; x
fi
code tls_certificate_key="$tls_certificate_key"
[ -f "$tls_certificate" ] || fileMustExists "$tls_certificate"
[ -f "$tls_certificate_key" ] || fileMustExists "$tls_certificate_key"
____

INDENT+="    " \
rcm-dovecot-multiple-certificate $isfast \
    --ssl-cert="$tls_certificate" \
    --ssl-key="$tls_certificate_key" \
    --fqdn="$fqdn" \
    --additional-config-file="$DOVECOT_CONFIG_FILE_ISPCONFIG" \
    ; [ ! $? -eq 0 ] && x

exit 0

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# )
# VALUE=(
# --fqdn
# --tls-certificate
# --tls-certificate-key
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# CSV=(
# )
# EOF
# clear
