#!/bin/bash

RCM_EXTENSION_VERSION=0.11.0-alpha.7

# Usage Functions.
usage() {
    cat << EOF
Usage: rcm ispconfig init [options]

Options:
   --fqdn=FQDN
        Fully Qualified Domain Name of this server, for example: \`server1.example.org\`.
        Value available from command: hostname(-f), or other.
   --public-domain
        Make sure that --fqdn is public domain, this will trigger TLS request and DNS verification.
   --acme-client=[TLS]
        Select acme client to obtain TLS Certificate.
        Values available from command: rcm(plugin list ispconfig/acme-client).
        Conditional: Bypass if --public-domain is not added.
   --web-server=HTTP
        Select web server to build up virtual host.
        Values available from command: rcm(plugin list ispconfig/web-server).
   --dbms=DB
        Select database management system to store the data.
        Values available from command: rcm(plugin list ispconfig/dbms).
   --mail-server=SMTP
        Select the mail transfer agent. Values available from command: rcm(plugin list ispconfig/mail-server).
   --mailbox-handler=[IMAP]
        Select the mail delivery agent. Values available from command: rcm(plugin list mailbox-handler).
   --mail-filtering=SPAM
        Select the mail filtering daemon. Values available from command: rcm(plugin list ispconfig/mail-filtering).
        Conditional: Bypass if --mailbox-handler has no value.
   --os-setup=OS
        Select the variation OS setup. Values available from command: rcm(plugin list ispconfig/os-setup).
   --timezone=[ZONE]
        Set the timezone of this machine. Available values: Asia/Gaza, Asia/Ujung_Pandang, Asia/Jakarta, Asia/Makassar, Asia/Pontianak, Asia/Jayapura, or other.

Other Options (For expert only):
   --without-update-system
        Skip execute update system. Default to --with-update-system.
   --with-upgrade-system
        Execute upgrade system. Default to --without-upgrade-system.

Additional Options:
   rcm(-p plugin prompt ispconfig/os-setup [--os-setup] init)
   rcm(-p plugin prompt ispconfig/acme-client [--acme-client] init)
   rcm(-p plugin prompt ispconfig/web-server [--web-server] init)
   rcm(-p plugin prompt ispconfig/dbms [--dbms] init)
   rcm(-p plugin prompt ispconfig/mail-server [--mail-server] init)
   rcm(-p plugin prompt mailbox-handler [--mailbox-handler] init)
   rcm(-p plugin prompt ispconfig/mail-filtering [--mail-filtering] init)
   rcm(-p plugin prompt ispconfig/acme-client [--acme-client] obtain)

Global Options.
   --version
        Print version of this script.
   --help
        Show this help.
EOF
}

# Prevent scripts from being executed directly.
[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --acme-client=*) acme_client="${1#*=}"; shift ;;
        --acme-client) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then acme_client="$2"; shift; fi; shift ;;
        --bypass-validation-is-installed) bypass_validation_is_installed=1; shift ;;
        --dbms=*) dbms="${1#*=}"; shift ;;
        --dbms) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then dbms="$2"; shift; fi; shift ;;
        --fqdn=*) fqdn="${1#*=}"; shift ;;
        --fqdn) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then fqdn="$2"; shift; fi; shift ;;
        --mailbox-handler=*) mailbox_handler="${1#*=}"; shift ;;
        --mailbox-handler) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then mailbox_handler="$2"; shift; fi; shift ;;
        --mail-filtering=*) mail_filtering="${1#*=}"; shift ;;
        --mail-filtering) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then mail_filtering="$2"; shift; fi; shift ;;
        --mail-server=*) mail_server="${1#*=}"; shift ;;
        --mail-server) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then mail_server="$2"; shift; fi; shift ;;
        --os-setup=*) os_setup="${1#*=}"; shift ;;
        --os-setup) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then os_setup="$2"; shift; fi; shift ;;
        --public-domain) public_domain=1; shift ;;
        --timezone=*) timezone="${1#*=}"; shift ;;
        --timezone) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then timezone="$2"; shift; fi; shift ;;
        --without-update-system) update_system=0; shift ;;
        --with-update-system) update_system=1; shift ;;
        --without-upgrade-system) upgrade_system=0; shift ;;
        --with-upgrade-system) upgrade_system=1; shift ;;
        --web-server=*) web_server="${1#*=}"; shift ;;
        --web-server) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then web_server="$2"; shift; fi; shift ;;
        --) shift
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    *) _new_arguments+=("$1"); shift ;;
                esac
            done
            ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

# Require.
require vendor/ijortengab/rcm/functions/classes/rcm-file.sh
require vendor/ijortengab/rcm/functions/classes/rcm-dir.sh
require vendor/ijortengab/rcm/functions/utility/find-string.sh
require vendor/ijortengab/rcm/functions/utility/sleep-extended.sh
require vendor/ijortengab/rcm/functions/utility/apt-install.sh
require vendor/ijortengab/rcm/functions/utility/backup-file.sh
require vendor/ijortengab/rcm/functions/utility/backup-dir.sh
require vendor/ijortengab/rcm/functions/utility/link-symbolic.sh
require vendor/ijortengab/bash/functions/array-diff.sh
require vendor/ijortengab/bash/functions/array-intersect.sh
require vendor/ijortengab/bash/functions/array-search.sh
require vendor/ijortengab/bash/functions/array-remove.sh
require vendor/ijortengab/ispconfig-autoinstaller/functions/parse-ini-file.sh

# ------------------------------------------------------------------------------

# Title.
title rcm ispconfig init
____

if [ -z "$fqdn" ];then
    error "Argument --fqdn is required."; x
fi

if [ -z "$acme_client" ];then
    error "Argument --acme-client is required."; x
fi

if [ -z "$web_server" ];then
    error "Argument --web-server is required."; x
fi

if [ -z "$dbms" ];then
    error "Argument --dbms is required."; x
fi

if [ -z "$os_setup" ];then
    error "Argument --os-setup is required."; x
fi

if [ -z "$mail_server" ];then
    error "Argument --mail-server is required."; x
fi

if [ -n "$mailbox_handler" ];then
    if [ -z "$mail_filtering" ];then
        error "Argument --mail-filtering is required."; x
    fi
fi

[ -n "$RCM_DEBUG" ] && chapter Variable dump.
[ -n "$RCM_DEBUG" ] && code 'web_server="'$web_server'"'
[ -n "$RCM_DEBUG" ] && code 'dbms="'$dbms'"'
[ -n "$RCM_DEBUG" ] && code 'os_setup="'$os_setup'"'
[ -n "$RCM_DEBUG" ] && code 'timezone="'$timezone'"'
[ -n "$RCM_DEBUG" ] && code 'mailbox_handler="'$mailbox_handler'"'
[ -n "$RCM_DEBUG" ] && code 'mail_filtering="'$mail_filtering'"'
[ -n "$RCM_DEBUG" ] && code 'public_domain="'$public_domain'"'
[ -n "$RCM_DEBUG" ] && ____

# Boolean default to TRUE.
[ -z "$update_system" ] && update_system=1; [ "$update_system" == 0 ] && update_system=

# Boolean default to FALSE.
[ "$upgrade_system" == 0 ] && upgrade_system=

RCM_DO_UPDATE_SYSTEM="$update_system"
RCM_DO_UPGRADE_SYSTEM="$upgrade_system"

____

# @todo, how about ntp

RCM_OS_TIMEZONE="$timezone"

include `rcm plugin run-method ispconfig/os-setup $os_setup define`

include `rcm plugin run-method ispconfig/os-setup $os_setup init`

# Dibutuhkan oleh rcm ispconfig init.
application=
application+=' net-tools'
application+=' pwgen'
apt-install $application

include `rcm plugin run-method ispconfig/acme-client $acme_client init`

include `rcm plugin run-method ispconfig/web-server $web_server init`

include `rcm plugin run-method ispconfig/dbms $dbms init`

include `rcm plugin run-method ispconfig/mail-server $mail_server init`

if [ -n "$mailbox_handler" ];then

    include `rcm plugin run-method mailbox-handler $mailbox_handler init`

    include `rcm plugin run-method ispconfig/mail-filtering $mail_filtering init`

fi

chapter Take a break.
_ Begin to Setup; _.
sleep-extended 3 30
____

include `rcm plugin run-method ispconfig/mail-server $mail_server setup`

if [ -n "$mailbox_handler" ];then

    include `rcm plugin run-method ispconfig/mail-filtering $mail_filtering setup`

fi

include `rcm plugin run-method ispconfig/dbms $dbms setup`

include `rcm plugin run-method ispconfig/web-server $web_server setup`

if [ -n "$public_domain" ];then

    RCM_FQDN=$(</etc/mailname)

    include `rcm plugin run-method ispconfig/acme-client $acme_client obtain`

    include `rcm plugin run-method ispconfig/acme-client $acme_client define`

    [ -n "$RCM_TLS_CERTIFICATE" ] || { red "Unable to proceed, variable \$RCM_TLS_CERTIFICATE is empty."; x; }
    [ -n "$RCM_TLS_CERTIFICATE_KEY" ] || { red "Unable to proceed, variable \$RCM_TLS_CERTIFICATE_KEY is empty."; x; }

fi

RCM_WEB_SERVER="$web_server"
RCM_PUBLIC_DOMAIN="$public_domain"

include `rcm plugin run-method ispconfig/os-setup $os_setup setup`

include `rcm plugin run-method ispconfig/os-setup $os_setup post-setup`

chapter Take a break.
_ Everything is OK, "let's" dump variables.; _.
sleep-extended 3
____

databaseCredentialIspconfig() {
    local php_fpm_user prefix path
    php_fpm_user=ispconfig
    prefix=$(getent passwd "$php_fpm_user" | cut -d: -f6 )
    path="${prefix}/interface/lib/config.inc.php"
    db_user=$(php -r "include '$path';echo DB_USER;")
    db_user_password=$(php -r "include '$path';echo DB_PASSWORD;")
}
websiteCredentialIspconfig() {
    local ISPCONFIG_WEB_USER_PASSWORD
    path=/usr/local/share/ispconfig/credential/website
    [ -f "$path" ] || fileMustExists "$path"
    . "$path"
    ispconfig_web_user_password=$ISPCONFIG_WEB_USER_PASSWORD
}

chapter MySQL Credentials.
databaseCredentialIspconfig
_ ' - 'username: $db_user; _.
_ '   'password: $db_user_password; _.
____

chapter ISPConfig Credentials.
websiteCredentialIspconfig
_ ' - 'username: admin; _.
_ '   'password: $ispconfig_web_user_password; _.
____

exit 0

# parse-options.sh \
# --with-end-options-double-dash \
# --with-end-options-specific-operand \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# --bypass-validation-is-installed
# --public-domain
# )
# VALUE=(
# --fqdn
# --timezone
# --web-server
# --mail-server
# --mailbox-handler
# --mail-filtering
# --dbms
# --os-setup
# --acme-client
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# CSV=(
    # 'long:--with-update-system,parameter:update_system'
    # 'long:--without-update-system,parameter:update_system,flag_option:reverse'
    # 'long:--with-upgrade-system,parameter:upgrade_system'
    # 'long:--without-upgrade-system,parameter:upgrade_system,flag_option:reverse'
# )
# OPERAND=(
# )
# EOF
# clear
